# 设置参考文档: https://atri.imki.moe/install/configuration-bot/
ConfigVersion: "1.2.0"

BotConfig:
  host: "{host}"
  port: {port}
  debug: false
  superusers: [{superusers}]
  nickname: ["ATRI", "Atri", "atri", "亚托莉", "アトリ"]
  command_start: ["", "/"]
  command_sep: ["."]
  session_expire_timeout: 60
  access_token: ""
  proxy: "{proxy}"
  request_timeout: 5

WithGoCQHTTP:
  enabled: {is_use_with_gocq}
  accounts:
    - uin: {uin}
      password: "{password}"
      protocol: {protocol}
  
  download_domain: "{download_domain}"
  download_version: "v1.0.0-rc3"

  gocq_webui_username: "ATRI"
  gocq_webui_password: "ATRI1314000***"

SauceNAO:
  key: "{saucenao_key}"

Setu:
  reverse_proxy: true
  reverse_proxy_domain: "i.pixiv.re"

GeoIP:
  account_id: 0
  license_key: ""
